Added -T option for packing from a file listing.
earlephilhower/mklittlefs pull request #34
Opened 2023-09-19 16:18 UTC by zvonler

Was looking for a bit more flexibility when adding files from a directory that might contain unwanted files. Added a small test framework too, it may need some adjustments to be platform independent, as of now I've only tested on MacOS.

2023-09-19 17:30 UTC, earlephilhower requested changes
First of all, thanks very much for adding tests!  One minor thing Win32 related here, I think.

2023-09-19 17:56 UTC, zvonler commented on main.cpp
> +        if (srcpath[linelen - 1] == '\n') {
Sure, didn't know if supporting DOS files without complaint was desired - I'll update.

2023-09-22 15:49 UTC, earlephilhower commented
Sorry, I just got back from a business trip last night.  I'll look at this in the next day or two.  Thanks for adding Windows support!

2023-09-22 16:02 UTC, zvonler commented
> Sorry, I just got back from a business trip last night. I'll look at this in the next day or two. Thanks for adding Windows support!

Right on, no problem.

2023-09-22 21:44 UTC, earlephilhower approved these changes
Thanks!

2023-09-22 21:45 UTC, merged

2023-09-23 14:37 UTC, Jason2866 commented
@earlephilhower Fails to compile with Windows. Used the docker build env
See GH Actions run https://github.com/Jason2866/mklittlefs/actions/runs/6284288146/job/17065511128